version: '3.7'

services:
  guestbook:
    container_name: guestbook
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - '8002:8001'
    environment:
      - NODE_ENV=development
